**

!Dockerfile
!Cargo.toml
!Cargo.lock
!build.rs
!package.json
!bun.lock
!LICENSE
!about.toml
!about.hbs

!migrations
!migrations/**
!patches
!patches/**
!src
!src/**
!web
!web/**

web/build
web/.svelte-kit
web/node_modules
web/**/.env*
web/**/*.key
web/**/*.pem
web/**/*.db*
web/**/*secret*
